name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: useblacksmith/cache@v5
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: "18.x"
          scope: "@dietdoctor"
      - name: Install dependencies
        run: yarn
      - name: Install dependencies
        run: yarn run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run semantic-release
